### ISSUE TITLE
Pre select days

### ISSUE THREAD

**Issue by Ulixestoitaca** [nikolasmagno/jquery-weekdays#1]
Hello,

thank you for your useful tool.
I just wonder if it would be possible to preselect days by jquery: I need user to choose weekdays, store on db then show them again but I do not understand how to show days as selected by default

**Comment by nikolasmagno** [comment]
Hi,
It's a nice idea, give me some time and i'll implement it. If you wanna contribute you'll be welcomed.

**Comment by nikolasmagno** [comment]
Hi,
I made a new feature to support pre-selected indexes, so you can use it. 

Enjoy it!

**Comment by Ulixestoitaca** [comment]
Really? I will try it asap

Thank you!

**Comment by Ulixestoitaca** [comment]
Hello,
Thanks for your update. 
There is a little bug I think, I'll try to explain step-by-step. 

1 user select for example Sunday monday
2 the code correctly displays Sunday and Monday as pre-selected days
3 the user try to add Friday and saturday
4 pre-selected days now are supposed to be Sunday Monday Friday Saturday but it works not like this: even if pre-selected Sunday and Monday are not treated as selected
5 now pre-selected days are now only Friday and saturday

I hope I explained the point

**Comment by nikolasmagno** [comment]
Hi,
Sry, after a long time I fixed this bug. 

It's avaliable in v1.1.1 release.

**Comment by Ulixestoitaca** [comment]
great job, now it is perfect!
